language: cpp

compiler:
  - clang

notifications:
    email:
        recipients:
            - max.sagebaum@scicomp.uni-kl.de
            - tim.albring@scicomp.uni-kl.de
        on_success: never
        on_failure: always
script: 
  - cd tests/
  - make CXX=clang++
